// Comprehensive UP Location Data based on Official District and Block Mapping.
// Format: District -> Block -> [Villages/Areas]

export const upLocationData = {
    "Agra": {
        "ACHHNERA": ["Achhnera Town", "Main Market", "Railway Colony"],
        "AKOLA": ["Akola Village", "Brahman Nagar"],
        "BAH": ["Bah Town", "Kacchapura"],
        "BARAULI AHIR": ["Barauli", "Ahir Village"],
        "BICHPURI": ["Bichpuri", "University Area"],
        "ETMADPUR": ["Etmadpur Town", "Chauraha"],
        "FATEHABAD": ["Fatehabad Town", "Nai Basti"],
        "FATEHPUR SIKRI": ["Sikri Fort Area", "Dargah Colony"],
        "JAGNER": ["Jagner Town", "Old Market"],
        "JAITPUR KALAN": ["Jaitpur", "Kalan Village"],
        "KHANDAULI": ["Khandauli", "Agra Road"],
        "KHERAGARH": ["Kheragarh", "Tehsil Area"],
        "PINAHAT": ["Pinahat Town", "River Side"],
        "SAIYAN": ["Saiyan", "NH2 Crossing"],
        "SHAMSABAD": ["Shamsabad", "Garden Colony"]
    },
    "Aligarh": {
        "AKRABAD": ["Akrabad Village", "Main Market"],
        "ATRAULI": ["Atrauli Town", "Tehsil Road"],
        "BIJAULI": ["Bijauli Town", "Station Area"],
        "CHANDAUS": ["Chandaus", "Old City"],
        "DHANIPUR": ["Dhanipur", "Airport Road"],
        "GANGIRI": ["Gangiri Town", "Market Area"],
        "GONDA": ["Gonda Village", "Central Aligarh"],
        "IGLAS": ["Iglas Town", "Education Hub"],
        "JAWAN": ["Jawan Sikandarpur", "Power Plant Area"],
        "KAIR": ["Kair Town", "Local Market"],
        "LODHA": ["Lodha", "University Peripheral"],
        "TAPPAL": ["Tappal Town", "Expressway Intersection"]
    },
    "Prayagraj": {
        "BAHRIYA": ["Bahriya Town", "Local Market"],
        "BHARWARI": ["Bharwari Station", "Town Area"],
        "CHAIL": ["Chail Town", "Tehsil Area"],
        "DHANUPUR": ["Dhanupur Village", "Market"],
        "HANDIA": ["Handia Town", "NH2 Side"],
        "JASRA": ["Jasra Town", "Station Road"],
        "KAUNDHIYARA": ["Kaundhiyara", "Main Village"],
        "KARCHANA": ["Karchana Town", "Tehsil Office"],
        "KORAON": ["Koraon Town", "Border Area"],
        "MANDA": ["Manda Road", "Palace Area"],
        "MAU AIMA": ["Mau Aima Town", "Market Area"],
        "MEJA": ["Meja Road", "Power Plant Area"],
        "NAGAR": ["Allahabad City", "Civil Lines"],
        "NAINI": ["Naini Industrial Area", "Bridge Side"],
        "PHULPUR": ["Phulpur Town", "IFFCO Colony"],
        "SAIDABAD": ["Saidabad Village", "Market"],
        "SHANKARGARH": ["Shankargarh Town", "Stone Quarry Area"],
        "SORAON": ["Soraon Town", "Tehsil Area"],
        "URAON": ["Uraon", "Local Area"]
    },
    "Ambedkar Nagar": {
        "AKBARPUR": ["Akbarpur City", "Collectorate Area"],
        "BASKHARI": ["Baskhari Town", "Market"],
        "BHITIA": ["Bhitia", "Village Area"],
        "BHUYAN": ["Bhuyan", "Main Village"],
        "JALALPUR": ["Jalalpur Town", "Handloom Hub"],
        "KATEHARI": ["Katehari Station", "Market"],
        "RAMNAGAR": ["Ramnagar", "Local Area"],
        "TANDA": ["Tanda City", "Thermal Power Area"]
    },
    "Amethi": {
        "AMETHI": ["Amethi Town", "Railway Station"],
        "BASKHARI": ["Baskhari", "Market Area"],
        "BHADAR": ["Bhadar", "Local Area"],
        "GURUHARRAI": ["Guruharrai", "Village Area"],
        "JAMO": ["Jamo Town", "Main Market"],
        "JAGDISHPUR": ["Jagdishpur Industrial Area", "BHEL Colony"],
        "SANGIPUR": ["Sangipur", "Market Area"],
        "SHIVGARH": ["Shivgarh Town", "Palace Area"],
        "SULTANPUR": ["Border Side", "Local Area"],
        "TILOI": ["Tiloi Town", "Tehsil Area"]
    },
    "Amroha": {
        "AMROHA": ["Amroha City", "Joya Road"],
        "DHANAURA": ["Dhanaura Town", "Sugar Mill Road"],
        "GAJRAULA": ["Gajraula Industrial Area", "NH24"],
        "HASSANPUR": ["Hassanpur Town", "Market Area"],
        "JOYA": ["Joya Road", "Main Crossing"]
    },
    "Auraiya": {
        "ACHALDA": ["Achalda Station", "Town Area"],
        "AIYAH": ["Aiyah", "Village Area"],
        "AURAIYA": ["Auraiya City", "Main Chauraha"],
        "BIDHUNA": ["Bidhuna Town", "Tehsil Area"],
        "ERAWAT": ["Erawat", "Local Area"],
        "SAHAR": ["Sahar Village", "Market"]
    },
    "Azamgarh": {
        "AHRAULA": ["Ahraula Town", "Main Market"],
        "ATRAULI": ["Atrauli Town", "Local Area"],
        "AZAMGARH": ["Azamgarh City", "Civil Lines"],
        "BILARIAGANJ": ["Bilariaganj Town", "Market"],
        "BURHANPUR": ["Burhanpur", "Tehsil Area"],
        "DEWA": ["Dewa Village", "Local Area"],
        "DOHRIGHAT": ["Dohrighat Town", "River Bank"],
        "JAHANAGANJ": ["Jahanaganj", "Main Crossing"],
        "KOELS": ["Koels", "Village Area"],
        "LALGANJ": ["Lalganj Town", "Market Area"],
        "MAHARAJGANJ": ["Maharajganj Town", "Sugar Mill Area"],
        "MAU": ["Border Area", "Local Village"],
        "MEHNAGAR": ["Mehnagar Town", "Fort Area"],
        "NIZAMABAD": ["Nizamabad Town", "Black Pottery Hub"],
        "PALHNI": ["Palhni", "City Peripheral"],
        "PHULPUR": ["Phulpur Town", "Market Area"],
        "SAGRI": ["Sagri", "Tehsil Area"],
        "TAJPUR": ["Tajpur", "Local Area"]
    },
    "Baghpat": {
        "BAGHPAT": ["Baghpat Town", "Collectorate"],
        "BARAUT": ["Baraut City", "College Area"],
        "CHHAPRAULI": ["Chhaprauli Town", "Local Market"],
        "KHEKRA": ["Khekra Town", "Industrial Area"],
        "TIKRI": ["Tikri Town", "Main Road"]
    },
    "Bahraich": {
        "BAHRAICH": ["Bahraich City", "Dargah Area"],
        "BALHA": ["Balha Town", "Nanpara Road"],
        "CHITTAURA": ["Chittaura", "Ashram Area"],
        "FAKHARPUR": ["Fakharpur Village", "Market"],
        "GAISARI": ["Gaisari", "Local Area"],
        "HARIYA": ["Hariya", "Village Area"],
        "IKOULI": ["Ikouli Town", "Sravasti Road"],
        "KAISERGANJ": ["Kaiserganj Town", "Market Area"],
        "MAHASI": ["Mahasi", "Tehsil Area"],
        "MIHINPURWA": ["Mihinpurwa Town", "Katerniaghat Gate"],
        "NANPARA": ["Nanpara Town", "Station Area"],
        "PAYAGPUR": ["Payagpur Station", "Market"],
        "RAMPUR": ["Rampur", "Village Area"],
        "SHIVPUR": ["Shivpur", "Local Area"],
        "TEJWAPUR": ["Tejwapur", "Market Area"]
    },
    "Ballia": {
        "BALLIA": ["Ballia City", "Banaras Road"],
        "BANSDIH": ["Bansdih Town", "Market"],
        "BELTHARA ROAD": ["Belthara Road Town", "Station Area"],
        "BERUARHARI": ["Beruarhari Village", "Market Area"],
        "BHIMPURA": ["BhimpuraTown", "Main Village"],
        "BILTHRA ROAD": ["Bilthra Road", "Market"],
        "CHILAKHAR": ["Chilakhar Village", "Market"],
        "DUBHAR": ["Dubhar Village", "Main Crossing"],
        "GARWAR": ["Garwar Town", "Market Area"],
        "HANUMANGANJ": ["Hanumanganj", "Local Market"],
        "MANIAR": ["Maniar Town", "River Side"],
        "NAGRA": ["Nagra Town", "Main Chauraha"],
        "NASRIGANJ": ["Nasriganj", "Village Area"],
        "RATANPURA": ["Ratanpura Town", "Market"],
        "SAHATWAR": ["Sahatwar Town", "Station Road"],
        "SIAR": ["Siar Town", "Local Area"]
    },
    "Balrampur": {
        "BALRAMPUR": ["Balrampur City", "Palace Area"],
        "GAURI CHAURAHA": ["Gauri Chauraha", "Market"],
        "GAURIPUR": ["Gauripur", "Village Area"],
        "HARAIYA SATGHARWA": ["Haraiya", "Forest Area"],
        "KAPTANGANJ": ["Kaptanganj Town", "Local Market"],
        "PANCHPEDWA": ["Panchpedwa Town", "Near Border"],
        "REHRA BAZAR": ["Rehra Bazar", "Town Area"],
        "SHRI DATTAGANJ": ["Dattaganj Town", "Market"],
        "TULSIPUR": ["Tulsipur Town", "Devipatan Temple"],
        "UTRAULA": ["Utraula Town", "Main Market"]
    },
    "Banda": {
        "ATARRA": ["Atarra Town", "University Area"],
        "BABERU": ["Baberu Town", "Tehsil Area"],
        "BANDA": ["Banda City", "Civil Lines"],
        "BISANDA": ["Bisanda Town", "Local Area"],
        "CHITRAKOOT DHAM": ["Karwi Town", "Religious Hub"],
        "JASPURA": ["Jaspura Village", "Market"],
        "MAUDAHA": ["Maudaha Town", "Market Area"],
        "NARAINI": ["Naraini Town", "Tehsil Area"]
    },
    "Barabanki": {
        "BANGLA": ["Bangla", "Market Area"],
        "DARIYABAD": ["Dariyabad Station", "Town Area"],
        "FATEHPUR": ["Fatehpur Town", "Sugar Mill Road"],
        "HAIDERGARH": ["Haidergarh Town", "NH56"],
        "HARAKH": ["Harakh Village", "Market Area"],
        "NAWABGANJ": ["Nawabganj Town", "City Centre"],
        "RAMSANEHIGHAT": ["Ramsanehighat", "Tehsil Area"],
        "SIDHAUR": ["Sidhaur Town", "Local Area"],
        "SIRAULI GAUSPUR": ["Gauspur Town", "Asmanpur"],
        "SULTANPUR": ["Border Village", "Local Area"],
        "TRIVENIGANJ": ["Triveniganj", "Village Area"],
        "ZAFARGANJ": ["Zafarganj Town", "Market area"]
    },
    "Bareilly": {
        "ALIGANJ": ["Aliganj Town", "Local Area"],
        "BAREILLY": ["Bareilly City", "Civil Lines"],
        "BAHERI": ["Baheri Town", "Sugar Mill Area"],
        "BHUTA": ["Bhuta Village", "Market"],
        "BILASPUR": ["Bilaspur Town", "Rampur Road"],
        "BITHRI CHAINPUR": ["Bithri", "Industrial Area"],
        "FATEHGANJ EAST": ["Fatehganj Town", "NH24"],
        "FATEHGANJ WEST": ["Fatehganj Town", "Rubber Factory"],
        "FARIDPUR": ["Faridpur Town", "Invertis Area"],
        "JALILPUR": ["Jalilpur", "Village Area"],
        "KYARA": ["Kyara Village", "Local Area"],
        "NAWABGANJ": ["Nawabganj Town", "Market Area"],
        "RAMNAGAR": ["Ramnagar Town", "Tehsil Area"],
        "SHERGARH": ["Shergarh Town", "Main Chauraha"],
        "SHISHGARH": ["Shishgarh Town", "Local Market"],
        "UNDH": ["Undh", "Village Area"]
    },
    "Basti": {
        "BAHADURPUR": ["Bahadurpur Town", "Market"],
        "BASTI": ["Basti City", "Civil Lines"],
        "DHANNAURA": ["Dhannaura", "Local Area"],
        "HARRAIYA": ["Harraiya Town", "Tehsil Area"],
        "KAPTANGANJ": ["Kaptanganj Town", "Market Area"],
        "MAHONA": ["Mahona Village", "Market Area"],
        "PARSHURAMPUR": ["Parshurampur", "Local Town"],
        "RAMNAGAR": ["Ramnagar Town", "Tehsil Area"],
        "SALTAUWA GOPALPUR": ["Saltauwa", "Village Area"],
        "SAURAI": ["Saurai", "Local Market"],
        "VIKAS NAGAR": ["Vikas Nagar", "City Extension"]
    },
    "Bijnor": {
        "AFZALGARH": ["Afzalgarh Town", "Market Area"],
        "ALLAHABAD": ["Mohalla Area", "Village"],
        "BIJNOR": ["Bijnor City", "Civil Lines"],
        "CHANDPUR": ["Chandpur Town", "Sugar Mill Road"],
        "DHAMPUR": ["Dhampur Town", "Station Area"],
        "HALDAUR": ["Haldaur Town", "Main Market"],
        "JALILPUR": ["Jalilpur Town", "Market Area"],
        "KIRATPUR": ["Kiratpur Town", "Local Area"],
        "KOTWALI": ["Kotwali Town", "Tehsil Area"],
        "MANDAWAR": ["Mandawar Town", "Old Market"],
        "NEHTAUR": ["Nehtaur Town", "Market Area"],
        "NOORPUR": ["Noorpur Town", "Local Area"],
        "SEOHARA": ["Seohara Town", "Sugar Mill Town"],
        "SHERKOT": ["Sherkot Town", "Brush Hub"]
    },
    "Budaun": {
        "ASAFPUR": ["Asafpur Station", "Village Area"],
        "BILSIDA": ["Bilsida Town", "Market"],
        "BINAVAR": ["Binavar Town", "Local Area"],
        "BUDAUN": ["Budaun City", "Civil Lines"],
        "DATAGANJ": ["Dataganj Town", "Tehsil Area"],
        "DEORANIA": ["Deorania Town", "Market Area"],
        "ISLAMNAGAR": ["Islamnagar Town", "Old City"],
        "KAKRALA": ["Kakrala Town", "Main Market"],
        "KUNDARKI": ["Kundarki", "Market"],
        "MIAO": ["Miao Village", "Local Area"],
        "QADIRGANJ": ["Qadirganj", "Town Area"],
        "SAHASWAN": ["Sahaswan Town", "Market Area"],
        "SAMRER": ["Samrer Village", "Market"],
        "SHASWAN": ["Sahaswan", "Tehsil Area"],
        "UDAIYA": ["Udaiya", "Local Area"]
    },
    "Bulandshahr": {
        "ANUPSHAHAR": ["Anupshahar Town", "Ghat Area"],
        "ARBANI": ["Arbani", "Village Area"],
        "BULANDSHAHR": ["Bulandshahr City", "Collectorate"],
        "CHHATA": ["Local Area", "Village"],
        "DADRI": ["Industrial Area", "Main Market"],
        "DANKAR": ["Dankar Town", "Local Market"],
        "DEBHAI": ["Debhai Town", "Tehsil Area"],
        "GULAOTHI": ["Gulaothi Town", "Main Chauraha"],
        "JAHANGIRABAD": ["Jahangirabad Town", "Market Area"],
        "KHURJA": ["Khurja Pottery Hub", "Station Area"],
        "LAKHOTI": ["Lakhoti Village", "Market Area"],
        "PACHGAON": ["Pachgaon Village", "Industrial Area"],
        "SHIKARPUR": ["Shikarpur Town", "Tehsil Area"],
        "SIANA": ["Siana Town", "Local Market"],
        "UNCHA GAON": ["Uncha Gaon", "Village Area"]
    },
    "Chandauli": {
        "CHAKIA": ["Chakia Town", "Fort Area"],
        "CHANDAULI": ["Chandauli City", "Collectorate"],
        "DHANAPUR": ["Dhanapur Town", "Market Area"],
        "GHAZIPUR": ["Border Village", "Local Area"],
        "MUGALSARAI": ["Mugalsarai City", "Railway Colony"],
        "NAUGARH": ["Naugarh Town", "Hilly Area"],
        "SAKALDIHA": ["Sakaldiha Town", "Tehsil Area"]
    },
    "Chitrakoot": {
        "CHITRAKOOT": ["Karwi City", "Ramghat"],
        "MAU": ["Mau Town", "Yamuna Bank"],
        "MANIKPUR": ["Manikpur Station", "Forest Area"],
        "RAMNAGAR": ["Ramnagar Town", "Tehsil Area"]
    },
    "Deoria": {
        "BARHAJ": ["Barhaj Town", "River Side"],
        "BHAGALPUR": ["Bhagalpur", "Market Area"],
        "BHATPAR RANI": ["Bhatpar Rani Town", "Tehsil Area"],
        "DEORIA": ["Deoria City", "Collectorate Area"],
        "DESHI DEORIA": ["Deshi Deoria Village", "Local Area"],
        "GAURI BAZAR": ["Gauri Bazar Town", "Sugar Mill Road"],
        "LAR": ["Lar Town", "Old Market"],
        "PATHARDEWA": ["Pathardewa Village", "Market Area"],
        "RAMPUR KARKHANA": ["Rampur Town", "Sugar Mill Area"],
        "RUDRAPUR": ["Rudrapur Town", "Tehsil Area"],
        "SALEMPUR": ["Salempur Town", "Tehsil Area"],
        "TARKULWA": ["Tarkulwa Town", "Local Area"]
    },
    "Etah": {
        "ALIGANJ": ["Aliganj Town", "Market Area"],
        "ETAH": ["Etah City", "Civil Lines"],
        "JAITHRA": ["Jaithra Town", "Main Chauraha"],
        "JALESAR": ["Jalesar Town", "Brass Hub"],
        "KASGANJ": ["Border Area", "Local Village"],
        "MARHARA": ["Marhara Town", "Old City"],
        "NIDHAULI KALAN": ["Nidhauli", "Market Area"],
        "SAHAWAR": ["Sahawar Town", "Station Road"],
        "SHIKOHABAD": ["Border Area", "Local Market"]
    },
    "Etawah": {
        "BARPURA": ["Barpura Village", "Market"],
        "BHARTHANA": ["Bharthana Town", "Market Area"],
        "CHAKAR NAGAR": ["Chakar Nagar Town", "Chambal Area"],
        "ETAWAH": ["Etawah City", "Civil Lines"],
        "JASWANT NAGAR": ["Jaswant Nagar Town", "Market Area"],
        "MAHEWA": ["Mahewa Town", "Main Chauraha"],
        "SAIFAI": ["Saifai Village", "Sports Hub"],
        "TAKHA": ["Takha", "Village Area"]
    },
    "Ayodhya": {
        "AKBARPUR": ["Border Village", "Local Area"],
        "BHIKHIYA CHAK": ["Bhikhiya Chak", "Market"],
        "FAIZABAD": ["Ayodhya City", "Civil Lines"],
        "JALALABAD": ["Jalalabad", "Town Area"],
        "MAYABAZAR": ["Mayabazar", "Main Market"],
        "MILKIPUR": ["Milkipur Town", "Tehsil Area"],
        "PURABAZAR": ["Purabazar", "Market Area"],
        "RUDAULI": ["Rudauli Town", "Tehsil Area"],
        "SOHWA": ["Sohwa Village", "Local Area"],
        "TARABGANJ": ["Border Town", "Local Area"]
    },
    "Farrukhabad": {
        "AMRITPUR": ["Amritpur Town", "Tehsil Area"],
        "FARRUKHABAD": ["Fatehgarh City", "Civil Lines"],
        "KAIMGANJ": ["Kaimganj Town", "Tehsil Area"],
        "KAMALGANJ": ["Kamalganj Town", "Market Area"],
        "MOHAMMADABAD": ["Mohammadabad Town", "Tehsil Road"],
        "RAJEPUR": ["Rajepur Village", "Market"],
        "SHAMSABAD": ["Shamsabad Town", "Local Area"]
    },
    "Fatehpur": {
        "AMRITPUR": ["Local Area", "Village"],
        "ASOTHAR": ["Asothar Town", "Market Area"],
        "AYAH": ["Ayah Village", "Main Crossing"],
        "BHITAURA": ["Bhitaura Town", "Market Area"],
        "DEOMAI": ["Deomai Town", "Local Area"],
        "FATEHPUR": ["Fatehpur City", "Civil Lines"],
        "HASWA": ["Haswa Town", "Station Area"],
        "HATHGAON": ["Hathgaon Town", "Main Chauraha"],
        "KHAJUHA": ["Khajuha Town", "Old Market"],
        "KHAGA": ["Khaga Town", "Tehsil Area"],
        "MALWAN": ["Malwan Village", "Industrial Area"],
        "VIJAYPUR": ["Vijaypur", "Village Area"]
    },
    "Firozabad": {
        "FIROZABAD": ["Firozabad City", "Glass Hub"],
        "HATHRAS": ["Border Village", "Local Area"],
        "JASRANA": ["Jasrana Town", "Tehsil Area"],
        "MADANPUR": ["Madanpur Village", "Market"],
        "SHIKOHABAD": ["Shikohabad Town", "Tehsil Area"],
        "TUNDLA": ["Tundla Railway Colony", "Station Area"],
        "USA": ["Usa Town", "Main Market"]
    },
    "Gautam Buddha Nagar": {
        "DADRI": ["Dadri City", "Railway Colony"],
        "JEWAR": ["Jewar Town", "Airport Site"],
        "VISRATKHAN": ["Greater Noida Extension", "Surajpur"]
    },
    "Ghaziabad": {
        "BHOJPUR": ["Bhojpur Town", "Market Area"],
        "GHAZIABAD": ["Noida City", "Indirapuram", "Vasundhara"],
        "LONI": ["Loni Town", "Border Area"],
        "MURADNAGAR": ["Muradnagar Town", "Ordnance Base"],
        "RAJAPUR": ["Rajapur Village", "Market Area"]
    },
    "Ghazipur": {
        "BARACHWAR": ["Barachwar Village", "Market"],
        "DEOKALI": ["Deokali Town", "Main Crossing"],
        "GHAZIPUR": ["Ghazipur City", "Opium Factory Road"],
        "JAKHANIA": ["Jakhania Town", "Tehsil Area"],
        "KARANDA": ["Karanda Village", "Market Area"],
        "KASIMABAD": ["Kasimabad Town", "Tehsil Area"],
        "MANIHARI": ["Manihari", "Village Area"],
        "MOHAMMADABAD": ["Mohammadabad Town", "Tehsil Area"],
        "NADWA": ["Nadwa Village", "Market"],
        "SAIDPUR": ["Saidpur Town", "Tehsil Area"],
        "ZAMANIA": ["Zamania Town", "Tehsil Area"]
    },
    "Gonda": {
        "BABHANAN": ["Babhanan Town", "Sugar Mill"],
        "CHANDRA": ["Chandra Village", "Market"],
        "DUMARIYAGANJ": ["Border Town", "Local Area"],
        "GAURIPUR": ["Gauripur Village", "Market"],
        "GONDA": ["Gonda City", "Civil Lines"],
        "ITWA": ["Itwa Town", "Tehsil Area"],
        "JHALA": ["Jhala Village", "Market Area"],
        "KATRA BAZAR": ["Katra Bazar", "Town Area"],
        "KHARGUPUR": ["Khargupur Town", "Local Market"],
        "MANKAPUR": ["Mankapur Town", "ITI Colony"],
        "MUNDERWA": ["Munderwa Town", "Sugar Mill"],
        "NAWABGANJ": ["Nawabganj Town", "Market Area"],
        "PANCHPERWA": ["Panchperwa Town", "Market Area"],
        "PARASPUR": ["Paraspur Town", "Local Market"],
        "TARABGANJ": ["Tarabganj Town", "Tehsil Area"],
        "WAZIRGANJ": ["Wazirganj Town", "Sugar Mill"]
    },
    "Gorakhpur": {
        "BAKSHI KA TALAB": ["Border Village", "Local Area"],
        "BHATHAT": ["Bhathat Town", "Market Area"],
        "BRAHMPUR": ["Brahmpur Village", "Market"],
        "CHARGHAWAN": ["Charghawan Town", "Market Area"],
        "CHIRGAON": ["Chirgaon Village", "Local Area"],
        "GAGHA": ["Gagha Town", "Main Chauraha"],
        "GORAKHPUR": ["Gorakhpur City", "Golghar", "Medical College"],
        "JANGAL KAURIA": ["Jangal Kauria", "Market Area"],
        "KHAJANI": ["Khajani Town", "Tehsil Area"],
        "KUSMHI": ["Kusmhi Forest Area", "Station"],
        "PIPRAICH": ["Pipraich Town", "Sugar Mill Road"],
        "SARDARNAGAR": ["Sardarnagar Town", "Local Market"],
        "URWA": ["Urwa Town", "Market Area"]
    },
    "Hamirpur": {
        "CHARKHARI": ["Charkhari Town", "Lake Side"],
        "HAMIRPUR": ["Hamirpur City", "Yamuna Bridge Side"],
        "MAUDAHA": ["Maudaha Town", "Market Area"],
        "RATH": ["Rath Town", "Tehsil Area"],
        "SARILA": ["Sarila Town", "Main Market"],
        "SUMERPUR": ["Sumerpur Industrial Area", "Station Road"]
    },
    "Hapur": {
        "DHAULANA": ["Dhaulana Town", "Tehsil Area"],
        "GARHMUKTESHWAR": ["Garh City", "Ganga Ghat"],
        "HAPUR": ["Hapur City", "Free Ganj"],
        "SIMBHAWALI": ["Simbhawali Town", "Sugar Mill Area"]
    },
    "Hardoi": {
        "AHIRORI": ["Ahirori Village", "Market"],
        "BAGHAULI": ["Baghauli Town", "Station Area"],
        "BILGRAM": ["Bilgram Town", "Tehsil Area"],
        "HARDOI": ["Hardoi City", "Cinema Chauraha"],
        "KACHHAUNA": ["Kachhauna Town", "Market Area"],
        "MADHOGANJ": ["Madhoganj Town", "Market Area"],
        "MALLAWAN": ["Mallawan Town", "Town Area"],
        "SANDI": ["Sandi Town", "Bird Sanctuary Road"],
        "SANDILA": ["Sandila Industrial Area", "Laddu Market"],
        "SHAHABAD": ["Shahabad Town", "Tehsil Area"],
        "TANDIYAWAN": ["Tandiyawan", "Market area"]
    },
    "Hathras": {
        "HATHRAS": ["Hathras City", "Main Market"],
        "MURSAN": ["Mursan Town", "Fort Side"],
        "SASNI": ["Sasni Town", "Market Road"],
        "SADABAD": ["Sadabad Town", "Tehsil Area"],
        "SIKANDRA RAO": ["Sikandra Rao Town", "Tehsil Area"]
    },
    "Jalaun": {
        "JALAUN": ["Jalaun City", "Tehsil Road"],
        "KALPI": ["Kalpi Town", "Yamuna Bank"],
        "KONCH": ["Konch Town", "Market Area"],
        "MADHOGARH": ["Madhogarh Town", "Tehsil Area"],
        "ORAI": ["Orai City", "Station Road"],
        "RAMPURA": ["Rampura Town", "Local Market"]
    },
    "Jaunpur": {
        "BADLAPUR": ["Badlapur Town", "Tehsil Area"],
        "BARSATHI": ["Barsathi Town", "Market Area"],
        "DHANAPUR": ["Border Village", "Local Area"],
        "JAUNPUR": ["Jaunpur City", "Civil Lines"],
        "KARANJAKALA": ["Karanjakala", "Market"],
        "KERAKAT": ["Kerakat Town", "Tehsil Area"],
        "KHUTHAN": ["Khuthan Town", "Local Market"],
        "MACHHLISHAHR": ["Machhlishahr Town", "Tehsil Area"],
        "MUNGRA BADSHAPUR": ["Badshapur Town", "Main Chauraha"],
        "RAMNAGAR": ["Ramnagar", "Village Area"],
        "SHAHGANJ": ["Shahganj Town", "Railway Colony"]
    },
    "Jhansi": {
        "BABINA": ["Babina Cantt Area", "Station"],
        "BAMOUR": ["Bamour Village", "Market"],
        "BARAGAON": ["Baragaon Town", "Tehsil Area"],
        "CHIRGAON": ["Chirgaon Town", "Local Area"],
        "GURSARAI": ["Gursarai Town", "Market Area"],
        "JHANSI": ["Jhansi City", "Elite Chauraha", "Civil Lines"],
        "MAURANIPUR": ["Mauranipur Town", "Tehsil Area"],
        "MOTH": ["Moth Town", "Tehsil Area"]
    },
    "Kannauj": {
        "CHHIBRAMAU": ["Chhibramau Town", "Tehsil Area"],
        "KANNAUJ": ["Kannauj City", "Perfume Market"],
        "SAURAIKHERA": ["Saurai Town", "Local Area"],
        "TALGRAM": ["Talgram Town", "Local Area"],
        "UMARDA": ["Umarda Village", "Market"]
    },
    "Kanpur Dehat": {
        "AKBARPUR": ["Akbarpur Town", "Eco Park Area"],
        "AMROHA": ["Border Village", "Local Area"],
        "DERAPUR": ["Derapur Town", "Tehsil Area"],
        "KANPUR DEHAT": ["Matei City", "Collectorate"],
        "RASULABAD": ["Rasulabad Town", "Tehsil Area"],
        "SAFEDABAD": ["Safedabad", "Town Area"],
        "SHEOLI": ["Sheoli Village", "Market Area"]
    },
    "Kanpur Nagar": {
        "BILHAUR": ["Bilhaur Town", "GTRoad"],
        "CHAUBEPUR": ["Chaubepur Town", "Market Area"],
        "GHATAMPUR": ["Ghatampur Town", "Tehsil Area"],
        "KALYANPUR": ["Kalyanpur City", "IIT Gateway"],
        "KANPUR": ["Kanpur City", "Civil Lines", "Kidwai Nagar"],
        "SARSAUL": ["Sarsaul Town", "Market Area"],
        "SHIVRAJPUR": ["Shivrajpur Town", "Market Road"]
    },
    "Kasganj": {
        "KASGANJ": ["Kasganj City", "Railway Colony"],
        "PATIALI": ["Patiali Town", "Market Area"],
        "SAHIBABAD": ["Sahibabad Town", "Local Area"],
        "SORON": ["Soron Town", "Ghat Area"]
    },
    "Kaushambi": {
        "KAUSHAMBI": ["Kaushambi Ruins Area", "Manjhanpur"],
        "MANJHANPUR": ["Manjhanpur Town", "Tehsil Area"],
        "MURATGANJ": ["Muratganj Market", "Main Highway"],
        "NEWADA": ["Newada Village", "Local area"],
        "SIRATHU": ["Sirathu Town", "Tehsil Area"]
    },
    "Kushinagar": {
        "CAPTAINGANJ": ["Captainganj Town", "Sugar Mill Road"],
        "DUDHAHI": ["Dudhahi Village", "Market Area"],
        "FAZIL NAGAR": ["Fazil Nagar Town", "Market Road"],
        "HATA": ["Hata Town", "Tehsil Area"],
        "KAPTANGANJ": ["Kaptanganj", "Village Area"],
        "KASYA": ["Kushinagar Temple City", "Kasya"],
        "KOTWA": ["Kotwa Village", "Local Area"],
        "PADRAUNA": ["Padrauna City", "Collectorate"],
        "RAMKOLA": ["Ramkola Town", "Sugar Mill"],
        "SEORHI ONKAR": ["Seorhi Town", "Market"],
        "SUCHIYAON": ["Suchiyaon", "Market area"],
        "TAMKUHI": ["Tamkuhi Road", "Station Area"]
    },
    "Lakhimpur Kheri": {
        "BEHAR": ["Behar Town", "Local Area"],
        "DHAVERA": ["Dhavera", "Village Area"],
        "GOLA": ["Gola Gokarannath City", "Temple Road"],
        "ISANAGAR": ["Isanagar Village", "Market Area"],
        "KHERI": ["Kheri Town", "Old Market"],
        "LAKHIMPUR": ["Lakhimpur City", "Civil Lines"],
        "MOHAMMADI": ["Mohammadi Town", "Tehsil Area"],
        "NIGHASAN": ["Nighasan Town", "Tehsil Area"],
        "OEL DHAR": ["Oel Village", "Market Road"],
        "PALIA": ["Palia Kalan Town", "Dudhwa Gateway"],
        "PASGAPUR": ["Pasgapur Village", "Market"],
        "RAMIA BEHRA": ["Ramia Village", "Local Area"]
    },
    "Lalitpur": {
        "BAR": ["Bar Town", "Local Area"],
        "LALITPUR": ["Lalitpur City", "Station Road"],
        "MAHRAUNI": ["Mahrauni Town", "Tehsil Area"],
        "TALBEHAT": ["Talbehat Town", "Fort Side"]
    },
    "Lucknow": {
        "CHINHAT": ["Chinhat Chauraha", "Kamta"],
        "GOSAINGANJ": ["Gosainganj Market", "Sultanpur Road"],
        "KAKORI": ["Kakori Town", "Martyr Memorial"],
        "LUCKNOW": ["Hazratganj", "Gomti Nagar", "Aliganj"],
        "MALIHAABAD": ["Malihabad Mango Belt", "Tehsil Area"],
        "MOHANLALGANJ": ["Mohanlalganj Town", "Market Area"],
        "SAROJINI NAGAR": ["Amausi", "Airport Peripheral", "Transport Nagar"]
    },
    "Maharajganj": {
        "ANANDNAGAR": ["Anandnagar Town", "Pharenda"],
        "GHUGHLI": ["Ghughli Town", "Sugar Mill Road"],
        "MAHARAJGANJ": ["Maharajganj City", "Collectorate"],
        "NICHLAUL": ["Nichlaul Town", "Tehsil Area"],
        "PARTAWAL": ["Partawal Market", "Main Crossing"],
        "PHARASMANDAL": ["Pharasmandal", "Village Area"],
        "SISWA": ["Siswa Bazar Town", "Sugar Mill"],
        "TAHIRPUR": ["Tahirpur", "Village Area"]
    },
    "Mahoba": {
        "CHARKHARI": ["Charkhari Town", "Old Fort"],
        "JAITPUR": ["Jaitpur Town", "Market"],
        "MAHOBA": ["Mahoba City", "Alha Udal Chowk"],
        "PANWARI": ["Panwari Village", "Market Area"]
    },
    "Mainpuri": {
        "BEWAR": ["Bewar Town", "Market Area"],
        "GHIROR": ["Ghiror Town", "Tehsil Area"],
        "KARHAL": ["Karhal Town", "Expressway Entry"],
        "KISHPANI": ["KishpaniVillage", "Market"],
        "KURAWALI": ["Kurawali Town", "Main Chauraha"],
        "MAINPURI": ["Mainpuri City", "Civil Lines"],
        "SHIKOHABAD": ["Border Village", "Local Area"]
    },
    "Mathura": {
        "CHHATA": ["Chhata Town", "Industrial Area"],
        "GOVERDHAN": ["Goverdhan Parikrama Path", "Temple Area"],
        "MATHURA": ["Mathura City", "Krishna Janmasthan", "Civil Lines"],
        "MAHOLI": ["Maholi Village", "Market Area"],
        "MAT": ["Mat Town", "Tehsil Area"],
        "NANDGAON": ["Nandgaon Town", "Temple Side"],
        "RAYA": ["Raya Town", "Main Market"],
        "SADABAD": ["SADABAD", "Village Area"],
        "SADAR": ["Mathura Cantt", "City Centre"],
        "SONKH": ["Sonkh Town", "Old Market"]
    },
    "Mau": {
        "DOHRIGHAT": ["Dohrighat Town", "Ghat Road"],
        "GHOSHI": ["Ghosi Town", "Market Area"],
        "MAU": ["Mau City", "Railway Colony"],
        "MAUNATH BHANJAN": ["Mau City", "Main Market"],
        "MOHAMMADABAD": ["Mohammadabad Town", "Local Area"],
        "PURANI": ["Purany Village", "Market Area"],
        "RATANPURA": ["Ratanpura Town", "Market Area"]
    },
    "Meerut": {
        "DAURALA": ["Daurala Town", "Sugar Mill Road"],
        "JANSAATH": ["Border Town", "Local Area"],
        "KHARKHAUDA": ["Kharkhauda Town", "Market"],
        "MAWANA": ["Mawana Town", "Sugar Mill Road"],
        "MEERUT": ["Meerut City", "Begum Bridge", "Civil Lines"],
        "SARDHANA": ["Sardhana Town", "Church Area"]
    },
    "Mirzapur": {
        "CHHANVEY": ["Chhanvey Village", "Market Area"],
        "HALIYA": ["Haliya Village", "Forest Area"],
        "JAMALPUR": ["Jamalpur Town", "Market"],
        "KON": ["Kon Village", "Market Area"],
        "LALGANJ": ["Lalganj Town", "Market Area"],
        "MAJHAWAN": ["Majhawan Town", "Main Road"],
        "MARIHAN": ["Marihan Town", "Tehsil Area"],
        "MIRZAPUR": ["Mirzapur City", "Vindhyachal Area", "Kotwali"],
        "NAGAR": ["City Area", "Main Market"],
        "PAHARI": ["Pahari Town", "Tehsil Area"],
        "SEWPRASAD": ["Sewprasad", "Market Area"]
    },
    "Moradabad": {
        "BILARI": ["Bilari Town", "Tehsil Area"],
        "CHAJLET": ["Chajlet Village", "Market Road"],
        "KANTH": ["Kanth Town", "Sugar Mill Road"],
        "MORADABAD": ["Moradabad City", "Brass Market", "Civil Lines"],
        "THAKURDWARA": ["Thakurdwara Town", "Tehsil Area"]
    },
    "Muzaffarnagar": {
        "BAGHRA": ["Baghra Town", "Main Chauraha"],
        "BUDHANA": ["Budhana Town", "Tehsil Area"],
        "CHARTHAWAL": ["Charthawal Town", "Market Area"],
        "JANSATH": ["Jansath Town", "Tehsil Area"],
        "KHATAULI": ["Khatauli Town", "Sugar Mill Side"],
        "MORNA": ["Morna Town", "Sugar Road"],
        "MUZAFFARNAGAR": ["Muzaffarnagar City", "Civil Lines"],
        "PURKAZI": ["Purkazi Town", "Dargah Area"],
        "SHAMLI": ["Border Town", "Local Area"],
        "THANA BHAVAN": ["Thana Bhavan", "Town area"]
    },
    "Pilibhit": {
        "AMARIA": ["Amaria Village", "Market Area"],
        "BARKHERA": ["Barkhera Town", "Sugar Mill Area"],
        "BISALPUR": ["Bisalpur Town", "Tehsil Area"],
        "LALORI KHERA": ["Lalori Khera", "Market area"],
        "MARORI": ["Marori", "Local Area"],
        "PILIBHIT": ["Pilibhit City", "Civil Lines"],
        "PURANPUR": ["Puranpur Town", "Tiger Reserve Area"]
    },
    "Pratapgarh": {
        "BABAGANJ": ["Babaganj Town", "Market"],
        "KUNDA": ["Kunda Town", "Market Area"],
        "LALGANJ": ["LALGANJ", "Tehsil Area"],
        "MANIKPUR": ["Manikpur GTRoad", "River Side"],
        "PANDUA": ["Pandua Village", "Local Area"],
        "PATTI": ["Patti Town", "Tehsil Area"],
        "PRATAPGARH": ["Pratapgarh City", "Civil Lines"],
        "RANIGANJ": ["Raniganj Village", "Market Area"],
        "SANGIPUR": ["Sangipur Town", "Tehsil Area"],
        "SHIVGARH": ["Shivgarh Village", "Market"]
    },
    "Rae Bareli": {
        "AMETHI": ["Border Village", "Local Area"],
        "DALMAU": ["Dalmau Town", "River Side"],
        "DEEH": ["Deeh Village", "Market Area"],
        "JAGDISHPUR": ["Industrial Peripheral", "Village"],
        "LALGANJ": ["Lalganj Town", "Rail Coach Factory"],
        "MAHARAJGANJ": ["Maharajganj Town", "Market Area"],
        "RAHATA": ["RahataVillage", "Market"],
        "RAE BARELI": ["Rae Bareli City", "Civil Lines"],
        "SALON": ["Salon Town", "Tehsil Area"],
        "SATAON": ["Sataon Village", "Market"],
        "SHIVGARH": ["Shivgarh Town", "Tehsil Area"],
        "UNCHAHAR": ["Unchahar Town", "NTPC Colony"]
    },
    "Rampur": {
        "BILASPUR": ["Bilaspur Town", "Tehsil Area"],
        "MILAK": ["Milak Town", "Market Area"],
        "RAMPUR": ["Rampur City", "Civil Lines"],
        "SHAHABAD": ["Shahabad Town", "Tehsil Area"],
        "SUAR": ["Suar Town", "Sugar Mill Area"],
        "TANDA": ["Tanda Town", "Industrial Area"]
    },
    "Saharanpur": {
        "BALLIA KHAD": ["Border Village", "Market"],
        "DEOBAND": ["Deoband City", "Seminary Area"],
        "GANGOH": ["Gangoh Town", "Market Area"],
        "NAGAL": ["Nagal Station Area", "Village"],
        "NANHATA": ["Nanhata Village", "Local Area"],
        "RAMPUR MANIHARAN": ["Rampur Town", "Tehsil Area"],
        "SAHARANPUR": ["Saharanpur City", "Civil Lines"],
        "SHEIKHPURA": ["Sheikhpura", "Industrial Area"]
    },
    "Sambhal": {
        "BAHJOI": ["Bahjoi Town", "District Headquarter Side"],
        "CHANDOUSI": ["Chandausi Town", "Station Area"],
        "GUNNAUR": ["Gunnaur Town", "Tehsil Area"],
        "SAMBHAL": ["Sambhal City", "Menthol Hub Area"]
    },
    "Sant Kabir Nagar": {
        "BELHAR KALA": ["Belhar Kala", "Village Area"],
        "KHALILABAD": ["Khalilabad City", "Industrial Area"],
        "MEHNDWAL": ["Mehendawal Town", "Market Area"],
        "SANT KABIR NAGAR": ["Maghar", "Kabir Sthal Area"]
    },
    "Bhadohi": {
        "ABHOLI": ["Abholi Village", "Market Area"],
        "AURAI": ["Aurai Town", "Main Chauraha"],
        "BHADOHI": ["Bhadohi City", "Station Area", "Carpet City"],
        "DEEGH": ["Deegh Village", "Market Area"],
        "GYANPUR": ["Gyanpur Town", "Tehsil Area"],
        "SURYA": ["Suriyawan Town", "Station Area"]
    },
    "Shahjahanpur": {
        "BANDA": ["Banda Town", "Local Area"],
        "BHADAIYAN": ["Bhadaiyan Village", "Market Area"],
        "DHAURAHARA": ["Dhaurahara Village", "Market"],
        "JALALABAD": ["Jalalabad Town", "Tehsil Area"],
        "KALAN": ["Kalan Town", "Market Road"],
        "KHUTAR": ["Khutar Town", "Market Area"],
        "MIRANPUR KATRA": ["Katra Town", "NH24"],
        "NIGOHI": ["Nigohi Station Area", "Market"],
        "POWAYAN": ["Powayan Town", "Tehsil Area"],
        "ROSA": ["Rosa Town", "Thermal Power Area"],
        "SHAHJAHANPUR": ["Shahjahanpur City", "Civil Lines"],
        "SIDHAULI": ["Sidhauli Town", "Local Area"],
        "TILHAR": ["Tilhar Town", "Tehsil Area"]
    },
    "Shamli": {
        "KANDHLA": ["Kandhla Town", "Market Area"],
        "SHAMLI": ["Shamli City", "Main Crossing"],
        "THANA BHAVAN": ["Thana Bhavan City", "Sugar Mill Road"],
        "UN": ["Un Town", "Local Area"]
    },
    "Shravasti": {
        "HARIHARPUR RANI": ["Hariharpur", "Market Area"],
        "ICHAURA": ["Ichaura Village", "Main Crossing"],
        "JAMUNAH": ["Jamunah Town", "Tehsil Area"],
        "SHRAVASTI": ["Shravasti City", "Buddhist Circuit Site"]
    },
    "Siddharthnagar": {
        "BANSI": ["Bansi Town", "Fort Area"],
        "BHANWAPUR": ["Bhanwapur Village", "Market Area"],
        "BIRDAPUR": ["Birdapur Town", "Local Market"],
        "DUMARIYAGANJ": ["Dumariyaganj Town", "Tehsil Area"],
        "ITWA": ["Itwa Town", "Tehsil Area"],
        "JOGIA": ["Jogia Village", "Market Area"],
        "KHALILABAD": ["Border Town", "Local Area"],
        "NAUGARH": ["Naugarh City", "Collectorate"],
        "SHOHARATGARH": ["Shoharatgarh City", "Railway Colony"],
        "UDHAULI": ["Udhauli", "Market Area"]
    },
    "Sitapur": {
        "BISWAN": ["Biswan Town", "Sugar Mill Area"],
        "GONDAL": ["Gondal Village", "Local Area"],
        "HARDI": ["Hardi Village", "Market Area"],
        "KHAIRABAD": ["Khairabad Town", "Old City"],
        "LAHARPUR": ["Laharpur Town", "Tehsil Area"],
        "MAHOLI": ["Maholi Town", "Tehsil Area"],
        "MISRIKH": ["Misrikh Town", "Religious Hub Area"],
        "PISAVA": ["Pisava Town", "Local Market"],
        "RAMPUR": ["Border Village", "Local Area"],
        "SIDHAULI": ["Sidhauli Town", "Market Area"],
        "SITAPUR": ["Sitapur City", "Civil Lines"]
    },
    "Sonbhadra": {
        "CHOPAN": ["Chopan Town", "River Bridge Side"],
        "DUDHI": ["Dudhi Town", "Tehsil Area"],
        "GHORAWAL": ["Ghorawal Town", "Market Area"],
        "MYORPUR": ["Myorpur Town", "Hindalco Colony"],
        "NAGAR": ["Robertsganj City Area", "Station"],
        "OBRA": ["Obra City", "Thermal Power Colony"],
        "ROBERTSGANJ": ["Robertsganj City", "Collectorate Area"]
    },
    "Sultanpur": {
        "AMETHI": ["Border Town Area", "Village"],
        "BALDANAGAR": ["Baldanagar Market", "Main Road"],
        "DOSTPUR": ["Dostpur Town", "Market Area"],
        "JAMO": ["Village Peripheral", "Local Area"],
        "KADIPUR": ["Kadipur Town", "Tehsil Area"],
        "KUREBHAR": ["Kurebhar Town", "Local Market"],
        "LAMBHUA": ["Lambhua Town", "Tehsil Area"],
        "SULTANPUR": ["Sultanpur City", "Civil Lines"]
    },
    "Unnao": {
        "BANGARMAU": ["Bangarmau Town", "Market Area"],
        "BIGHAPUR": ["Bighapur Town", "Tehsil Area"],
        "FATEHPUR CHAURASI": ["Fatehpur Town", "Village Area"],
        "GAJJA": ["Gajja Village", "Market Area"],
        "HASANGANJ": ["Hasanganj Town", "Market Area"],
        "MAURAWAN": ["Maurawan Town", "Town Area"],
        "PURWA": ["Purwa Town", "Tehsil Area"],
        "SAFIPUR": ["Safipur Town", "Tehsil Area"],
        "UNNAO": ["Unnao City", "Civil Lines", "Shuklaganj"]
    },
    "Varanasi": {
        "ARAJILINES": ["Arajilines Town", "Market Area"],
        "CHOLAPUR": ["Cholapur Town", "Main Chauraha"],
        "HARUA": ["Harua Village", "Local Market"],
        "KASHIVIDYAPEETH": ["DLW Colony", "Varanasi City Peripheral"],
        "PINDRA": ["Pindra Town", "Airport Area"],
        "SEVAPURI": ["Sevapuri Town", "Station Area"],
        "VARANASI": ["Dashashwamedh", "Lanka", "Cantonment", "Sigra"]
    }
};

export const getDistricts = () => Object.keys(upLocationData);
export const getBlocks = (district) => upLocationData[district] ? Object.keys(upLocationData[district]) : [];
export const getVillages = (district, block) => upLocationData[district] && upLocationData[district][block] ? upLocationData[district][block] : [];
